console.log("                    Question 1: Variables and Functions");
console.log("Declaring, calling and returning values of variables");
console.log("Declare three variables using let, const");
console.log('');
console.log("Declare Your name (string), Your age (number) and a boolean");
let myName = "Famojuro Moyosore";
const myAge = 100;
let isStudent = true;
console.log("Logging out the three to console on separate lines");
console.log("");
console.log(myName);
console.log(myAge);
console.log(isStudent);